const DATA_TYPE_PDF = 'data:application/pdf;base64,';
const ESTADOS_GUIA = {
  RECOLECCION: 'RECOLECCION',
  CLASIFICACION: 'CLASIFICACION',
  RUTA_NACIONAL: 'RUTA_NACIONAL',
  REPARTO: 'REPARTO',
  ENTREGADO: 'ENTREGADO',
};
